### ISSUE TITLE
移动端输入法自带的表情，应该怎么存进数据库，然后怎么在PC端处理显示，在touch端处理显示，可以帮忙解答吗

### ISSUE THREAD

**Issue by liuzhiyang0113** [node-modules/emoji#23]
The expression on the mobile terminal input method, how should I put it in mysql

**Comment by hikoming** [comment]
输入值通过转化成json格式，把字符串转码成Unicode，存到数据库，取出来的时候，可以直接用

**Comment by liuzhiyang0113** [comment]
谢谢
